export default [
    {
      id: 1,
      name: "Moo Deng",
      species: "Pygmy Hippo",
      gender: "Male",
      activities: "Grazing, Exploring",
      location: "Chiang Mai, Thailand",
      age: 5,
      description:
        "Moo Deng is a beloved celebrity pygmy hippo known for his adorable look. Born in the lush fields of northern Thailand, he quickly captured the hearts of locals with his gentle nature and playful spirit. Moo Deng enjoys roaming the rolling hills and munching on fresh grass all day long.",
      image: "/images/moo-deng.png",
    },
    {
      id: 2,
      name: "Fu Bao",
      species: "Panda",
      gender: "Female",
      activities: "Climbing, Bamboo munching",
      location: "Everland, South Korea",
      age: 3,
      description:
        "Fu Bao is a famous giant panda who has gained international recognition for her adorable antics. Born in captivity, she is an ambassador for wildlife conservation efforts and loves to climb trees and snack on bamboo shoots. Her curious personality and cuddly appearance make her a star attraction.",
      image: "/images/fu-bao.jpeg",
    },
    {
      id: 4,
      name: "Koko",
      species: "Gorilla",
      gender: "Female",
      activities: "Sign Language, Painting",
      location: "California, USA",
      age: 46,
      description:
        "Koko was a groundbreaking gorilla celebrated worldwide for her ability to communicate using sign language. Her gentle demeanor and remarkable intelligence offered new insights into the emotional depth of primates. Koko spent her days conversing with her caregivers, painting, and forming deep bonds with those around her.",
      image: "/images/koko.jpg",
    },
    {
      id: 5,
      name: "Tama",
      species: "Cat",
      gender: "Female",
      activities: "Greeting visitors, Napping",
      location: "Wakayama, Japan",
      age: 9,
      description:
        "Tama gained fame as the feline stationmaster of Kishi Station in Wakayama, Japan. Credited with revitalizing local tourism, Tama greeted passengers and charmed everyone with her stationmaster hat. She enjoyed basking in the sun and took her daily naps in her own cozy station office.",
      image: "/images/tama.jpg",
    },
    {
      id: 6,
      name: "Cecil",
      species: "Lion",
      gender: "Male",
      activities: "Roaming, Roaring",
      location: "Hwange National Park, Zimbabwe",
      age: 13,
      description:
        "Cecil was a famous lion distinguished by his striking black-fringed mane. He roamed Hwange National Park, where he was a key figure in conservation research. His majestic presence and leadership of his pride made him an iconic figure of African wildlife, attracting tourists and scientists from around the globe.",
      image: "/images/cecil.jpg",
    },
    {
      id: 7,
      name: "Gloria",
      species: "Elephant",
      gender: "Female",
      activities: "Bathing, Trumpeting, Roaming",
      location: "Maasai Mara, Kenya",
      age: 12,
      description:
        "Gloria is a famous elephant renowned for her wisdom and gentle nature. Known as the matriarch of her herd, she leads with grace and inspires conservation efforts across Africa. Gloria's playful nature and deep bonds with her family have made her a beloved figure among wildlife enthusiasts.",
      image: "/images/gloria.png",
    },
    {
      id: 8,
      name: "Oscar",
      species: "Penguin",
      gender: "Male",
      activities: "Swimming, Sliding, Diving",
      location: "Halley, Antarctica",
      age: 4,
      description:
        "Oscar is a charismatic penguin known for his impeccable diving skills and endearing waddle. His adventures in the icy waters have been featured in numerous wildlife documentaries, making him a celebrated ambassador of Antarctic life. Oscar's charm and resilience make him a star among his colony.",
      image: "/images/oscar.png",
    },
    {
      id: 9,
      name: "Aurora",
      species: "Peacock",
      gender: "Female",
      activities: "Displaying, Dancing, Strutting",
      location: "Jaipur, India",
      age: 7,
      description:
        "Aurora is a dazzling peacock admired for her vibrant and intricate plumage. With a mesmerizing display of colors, she graces the gardens of Jaipur and has been celebrated in art and folklore. Aurora's elegant dance and regal presence symbolize beauty and pride in the rich cultural tapestry of India.",
      image: "/images/aurora.png",
    },
    {
      id: 10,
      name: "Zephyr",
      species: "Eagle",
      gender: "Male",
      activities: "Soaring, Hunting, Gliding",
      location: "Rocky Mountains, USA",
      age: 8,
      description:
        "Zephyr is an iconic eagle whose majestic flight and piercing gaze have earned him renown among bird enthusiasts. Soaring high above the Rocky Mountains, his impressive hunting skills and commanding presence make him a true symbol of freedom and wilderness.",
      image: "/images/zephyr.jpeg",
    }
  ];